// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: login/v1/login.proto

package loginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_login_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=authToken,proto3" json:"authToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_login_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignUpResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SignUpResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type LogInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInRequest) Reset() {
	*x = LogInRequest{}
	mi := &file_login_v1_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInRequest) ProtoMessage() {}

func (x *LogInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInRequest.ProtoReflect.Descriptor instead.
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{2}
}

func (x *LogInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LogInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LogInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logged        bool                   `protobuf:"varint,1,opt,name=logged,proto3" json:"logged,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=authToken,proto3" json:"authToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInResponse) Reset() {
	*x = LogInResponse{}
	mi := &file_login_v1_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInResponse) ProtoMessage() {}

func (x *LogInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInResponse.ProtoReflect.Descriptor instead.
func (*LogInResponse) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{3}
}

func (x *LogInResponse) GetLogged() bool {
	if x != nil {
		return x.Logged
	}
	return false
}

func (x *LogInResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogInResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetNewAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewAuthTokenRequest) Reset() {
	*x = GetNewAuthTokenRequest{}
	mi := &file_login_v1_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAuthTokenRequest) ProtoMessage() {}

func (x *GetNewAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*GetNewAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{4}
}

func (x *GetNewAuthTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetNewAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewAuthTokenResponse) Reset() {
	*x = GetNewAuthTokenResponse{}
	mi := &file_login_v1_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAuthTokenResponse) ProtoMessage() {}

func (x *GetNewAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_v1_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*GetNewAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_login_v1_login_proto_rawDescGZIP(), []int{5}
}

func (x *GetNewAuthTokenResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

var File_login_v1_login_proto protoreflect.FileDescriptor

const file_login_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x14login/v1/login.proto\x12\blogin.v1\"G\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"k\n" +
	"\x0eSignUpResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\tauthToken\x18\x03 \x01(\tR\tauthToken\"F\n" +
	"\fLogInRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"i\n" +
	"\rLogInResponse\x12\x16\n" +
	"\x06logged\x18\x01 \x01(\bR\x06logged\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\tauthToken\x18\x03 \x01(\tR\tauthToken\"<\n" +
	"\x16GetNewAuthTokenRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"7\n" +
	"\x17GetNewAuthTokenResponse\x12\x1c\n" +
	"\tauthToken\x18\x01 \x01(\tR\tauthToken2\xdd\x01\n" +
	"\fLoginService\x12;\n" +
	"\x06SignUp\x12\x17.login.v1.SignUpRequest\x1a\x18.login.v1.SignUpResponse\x128\n" +
	"\x05LogIn\x12\x16.login.v1.LogInRequest\x1a\x17.login.v1.LogInResponse\x12V\n" +
	"\x0fGetNewAuthToken\x12 .login.v1.GetNewAuthTokenRequest\x1a!.login.v1.GetNewAuthTokenResponseB\x18Z\x16proto/login/v1;loginv1b\x06proto3"

var (
	file_login_v1_login_proto_rawDescOnce sync.Once
	file_login_v1_login_proto_rawDescData []byte
)

func file_login_v1_login_proto_rawDescGZIP() []byte {
	file_login_v1_login_proto_rawDescOnce.Do(func() {
		file_login_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_v1_login_proto_rawDesc), len(file_login_v1_login_proto_rawDesc)))
	})
	return file_login_v1_login_proto_rawDescData
}

var file_login_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_login_v1_login_proto_goTypes = []any{
	(*SignUpRequest)(nil),           // 0: login.v1.SignUpRequest
	(*SignUpResponse)(nil),          // 1: login.v1.SignUpResponse
	(*LogInRequest)(nil),            // 2: login.v1.LogInRequest
	(*LogInResponse)(nil),           // 3: login.v1.LogInResponse
	(*GetNewAuthTokenRequest)(nil),  // 4: login.v1.GetNewAuthTokenRequest
	(*GetNewAuthTokenResponse)(nil), // 5: login.v1.GetNewAuthTokenResponse
}
var file_login_v1_login_proto_depIdxs = []int32{
	0, // 0: login.v1.LoginService.SignUp:input_type -> login.v1.SignUpRequest
	2, // 1: login.v1.LoginService.LogIn:input_type -> login.v1.LogInRequest
	4, // 2: login.v1.LoginService.GetNewAuthToken:input_type -> login.v1.GetNewAuthTokenRequest
	1, // 3: login.v1.LoginService.SignUp:output_type -> login.v1.SignUpResponse
	3, // 4: login.v1.LoginService.LogIn:output_type -> login.v1.LogInResponse
	5, // 5: login.v1.LoginService.GetNewAuthToken:output_type -> login.v1.GetNewAuthTokenResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_v1_login_proto_init() }
func file_login_v1_login_proto_init() {
	if File_login_v1_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_v1_login_proto_rawDesc), len(file_login_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_v1_login_proto_goTypes,
		DependencyIndexes: file_login_v1_login_proto_depIdxs,
		MessageInfos:      file_login_v1_login_proto_msgTypes,
	}.Build()
	File_login_v1_login_proto = out.File
	file_login_v1_login_proto_goTypes = nil
	file_login_v1_login_proto_depIdxs = nil
}
