version: "3.9"
services:
  message-service:
    build:
      context: .
      dockerfile: ./messageService/Dockerfile
    container_name: message-service
    ports:
      - "50051:50051"
    environment:
      - AUTH=${AUTH}
      - SERVICE_API_KEY=${MESSAGE_SERVICE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - nats
    networks:
      - app-network

  broadcast-service:
    build:
      context: .
      dockerfile: ./broadcast/Dockerfile
    container_name: broadcast-service
    ports:
      - "8081:8081"
    environment:
      - AUTH=${AUTH}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - message-service
      - nats
    networks:
      - app-network

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - MESSAGE_SERVICE_API_KEY=${MESSAGE_SERVICE_API_KEY}
      - ROOM_SERVICE_API_KEY=${ROOM_SERVICE_API_KEY}
      - AUTH=${AUTH}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - message-service
      - broadcast-service
      - room-service
    networks:
      - app-network

  room-service:
    build:
      context: .
      dockerfile: ./roomService/Dockerfile
    container_name: room-service
    ports:
      - "50052:50052"
    environment:
      - AUTH=${AUTH}
      - SERVICE_API_KEY=${ROOM_SERVICE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  nats:
    image: nats:latest
    ports:
      - "4222:4222" 
      - "8222:8222" 
    command: ["-js", "-m", "8222"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

