// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/message/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *EditMessageRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *EditMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMessageRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MessageActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageActionResponse) Reset() {
	*x = MessageActionResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageActionResponse) ProtoMessage() {}

func (x *MessageActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageActionResponse.ProtoReflect.Descriptor instead.
func (*MessageActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Start         uint32                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	JwtToken      string                 `protobuf:"bytes,3,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_message_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetHistoryRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_message_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_message_v1_message_proto protoreflect.FileDescriptor

const file_proto_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/message/v1/message.proto\x12\n" +
	"message.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\"K\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"j\n" +
	"\x12EditMessageRequest\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"R\n" +
	"\x14DeleteMessageRequest\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"G\n" +
	"\x15MessageActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\\\n" +
	"\x11GetHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x14\n" +
	"\x05start\x18\x02 \x01(\rR\x05start\x12\x1b\n" +
	"\tjwt_token\x18\x03 \x01(\tR\bjwtToken\"E\n" +
	"\x12GetHistoryResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.message.v1.MessageR\bmessages2\xd1\x03\n" +
	"\x0eMessageService\x12P\n" +
	"\vSendMessage\x12\x1e.message.v1.SendMessageRequest\x1a!.message.v1.MessageActionResponse\x12P\n" +
	"\vEditMessage\x12\x1e.message.v1.EditMessageRequest\x1a!.message.v1.MessageActionResponse\x12T\n" +
	"\rDeleteMessage\x12 .message.v1.DeleteMessageRequest\x1a!.message.v1.MessageActionResponse\x12K\n" +
	"\n" +
	"GetHistory\x12\x1d.message.v1.GetHistoryRequest\x1a\x1e.message.v1.GetHistoryResponse\x12?\n" +
	"\x0eStreamMessages\x12\x16.google.protobuf.Empty\x1a\x13.message.v1.Message0\x01\x127\n" +
	"\x05Ready\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x12Z\x10proto/message/v1b\x06proto3"

var (
	file_proto_message_v1_message_proto_rawDescOnce sync.Once
	file_proto_message_v1_message_proto_rawDescData []byte
)

func file_proto_message_v1_message_proto_rawDescGZIP() []byte {
	file_proto_message_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)))
	})
	return file_proto_message_v1_message_proto_rawDescData
}

var file_proto_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_message_v1_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: message.v1.Message
	(*SendMessageRequest)(nil),    // 1: message.v1.SendMessageRequest
	(*EditMessageRequest)(nil),    // 2: message.v1.EditMessageRequest
	(*DeleteMessageRequest)(nil),  // 3: message.v1.DeleteMessageRequest
	(*MessageActionResponse)(nil), // 4: message.v1.MessageActionResponse
	(*GetHistoryRequest)(nil),     // 5: message.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 6: message.v1.GetHistoryResponse
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_proto_message_v1_message_proto_depIdxs = []int32{
	0, // 0: message.v1.GetHistoryResponse.messages:type_name -> message.v1.Message
	1, // 1: message.v1.MessageService.SendMessage:input_type -> message.v1.SendMessageRequest
	2, // 2: message.v1.MessageService.EditMessage:input_type -> message.v1.EditMessageRequest
	3, // 3: message.v1.MessageService.DeleteMessage:input_type -> message.v1.DeleteMessageRequest
	5, // 4: message.v1.MessageService.GetHistory:input_type -> message.v1.GetHistoryRequest
	7, // 5: message.v1.MessageService.StreamMessages:input_type -> google.protobuf.Empty
	7, // 6: message.v1.MessageService.Ready:input_type -> google.protobuf.Empty
	4, // 7: message.v1.MessageService.SendMessage:output_type -> message.v1.MessageActionResponse
	4, // 8: message.v1.MessageService.EditMessage:output_type -> message.v1.MessageActionResponse
	4, // 9: message.v1.MessageService.DeleteMessage:output_type -> message.v1.MessageActionResponse
	6, // 10: message.v1.MessageService.GetHistory:output_type -> message.v1.GetHistoryResponse
	0, // 11: message.v1.MessageService.StreamMessages:output_type -> message.v1.Message
	7, // 12: message.v1.MessageService.Ready:output_type -> google.protobuf.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_message_v1_message_proto_init() }
func file_proto_message_v1_message_proto_init() {
	if File_proto_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_v1_message_proto_rawDesc), len(file_proto_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_message_v1_message_proto_depIdxs,
		MessageInfos:      file_proto_message_v1_message_proto_msgTypes,
	}.Build()
	File_proto_message_v1_message_proto = out.File
	file_proto_message_v1_message_proto_goTypes = nil
	file_proto_message_v1_message_proto_depIdxs = nil
}
