// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	RequestStatus_REQUEST_STATUS_PENDING     RequestStatus = 1
	RequestStatus_REQUEST_STATUS_ACCEPTED    RequestStatus = 2
	RequestStatus_REQUEST_STATUS_REJECTED    RequestStatus = 3
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REQUEST_STATUS_UNSPECIFIED",
		1: "REQUEST_STATUS_PENDING",
		2: "REQUEST_STATUS_ACCEPTED",
		3: "REQUEST_STATUS_REJECTED",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_UNSPECIFIED": 0,
		"REQUEST_STATUS_PENDING":     1,
		"REQUEST_STATUS_ACCEPTED":    2,
		"REQUEST_STATUS_REJECTED":    3,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_proto_room_v1_room_proto_enumTypes[0]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{0}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // optional
	MemberCount   int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *Room) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Room) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Room) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMember) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *RoomMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type RoomInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	RoomUuid      string                 `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UsesLeft      int32                  `protobuf:"varint,3,opt,name=uses_left,json=usesLeft,proto3" json:"uses_left,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInvite) Reset() {
	*x = RoomInvite{}
	mi := &file_proto_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInvite) ProtoMessage() {}

func (x *RoomInvite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInvite.ProtoReflect.Descriptor instead.
func (*RoomInvite) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *RoomInvite) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *RoomInvite) GetUsesLeft() int32 {
	if x != nil {
		return x.UsesLeft
	}
	return 0
}

func (x *RoomInvite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RoomInvite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status        RequestStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=room.v1.RequestStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *JoinRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *JoinRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *JoinRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *JoinRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateRoomRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomResponse) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *CreateRoomResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type UpdateRoomNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomNameRequest) Reset() {
	*x = UpdateRoomNameRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomNameRequest) ProtoMessage() {}

func (x *UpdateRoomNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoomNameRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *UpdateRoomNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type GetUserRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoomsRequest) Reset() {
	*x = GetUserRoomsRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomsRequest) ProtoMessage() {}

func (x *GetUserRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{10}
}

type UserRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrivate     bool                   `protobuf:"varint,3,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoom) Reset() {
	*x = UserRoom{}
	mi := &file_proto_room_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoom) ProtoMessage() {}

func (x *UserRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoom.ProtoReflect.Descriptor instead.
func (*UserRoom) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *UserRoom) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *UserRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRoom) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UserRoom) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *UserRoom) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *UserRoom) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetUserRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*UserRoom            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoomsResponse) Reset() {
	*x = GetUserRoomsResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomsResponse) ProtoMessage() {}

func (x *GetUserRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRoomsResponse) GetRooms() []*UserRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetRoomMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersRequest) Reset() {
	*x = GetRoomMembersRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersRequest) ProtoMessage() {}

func (x *GetRoomMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersRequest.ProtoReflect.Descriptor instead.
func (*GetRoomMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoomMembersRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type GetRoomMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*RoomMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersResponse) Reset() {
	*x = GetRoomMembersResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersResponse) ProtoMessage() {}

func (x *GetRoomMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersResponse.ProtoReflect.Descriptor instead.
func (*GetRoomMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *GetRoomMembersResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *LeaveRoomRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveMemberRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UsesLeft      int32                  `protobuf:"varint,2,opt,name=uses_left,json=usesLeft,proto3" json:"uses_left,omitempty"`   //0 or negative is unlimited
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{17}
}

func (x *CreateInviteRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *CreateInviteRequest) GetUsesLeft() int32 {
	if x != nil {
		return x.UsesLeft
	}
	return 0
}

func (x *CreateInviteRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{18}
}

func (x *CreateInviteResponse) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type GetInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteRequest) Reset() {
	*x = GetInviteRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteRequest) ProtoMessage() {}

func (x *GetInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteRequest.ProtoReflect.Descriptor instead.
func (*GetInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{19}
}

func (x *GetInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type GetInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        *RoomInvite            `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteResponse) Reset() {
	*x = GetInviteResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteResponse) ProtoMessage() {}

func (x *GetInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteResponse.ProtoReflect.Descriptor instead.
func (*GetInviteResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{20}
}

func (x *GetInviteResponse) GetInvite() *RoomInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

type DeleteInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	RoomUuid      string                 `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInviteRequest) Reset() {
	*x = DeleteInviteRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInviteRequest) ProtoMessage() {}

func (x *DeleteInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInviteRequest.ProtoReflect.Descriptor instead.
func (*DeleteInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *DeleteInviteRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type JoinViaInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinViaInviteRequest) Reset() {
	*x = JoinViaInviteRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinViaInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinViaInviteRequest) ProtoMessage() {}

func (x *JoinViaInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinViaInviteRequest.ProtoReflect.Descriptor instead.
func (*JoinViaInviteRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{22}
}

func (x *JoinViaInviteRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type CreateJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinRequestRequest) Reset() {
	*x = CreateJoinRequestRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinRequestRequest) ProtoMessage() {}

func (x *CreateJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{23}
}

func (x *CreateJoinRequestRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *CreateJoinRequestRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type GetJoinRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinRequestsRequest) Reset() {
	*x = GetJoinRequestsRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinRequestsRequest) ProtoMessage() {}

func (x *GetJoinRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetJoinRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{24}
}

func (x *GetJoinRequestsRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type GetJoinRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*JoinRequest         `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinRequestsResponse) Reset() {
	*x = GetJoinRequestsResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinRequestsResponse) ProtoMessage() {}

func (x *GetJoinRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetJoinRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{25}
}

func (x *GetJoinRequestsResponse) GetRequests() []*JoinRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RespondToJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // Joining user id
	Decision      RequestStatus          `protobuf:"varint,3,opt,name=decision,proto3,enum=room.v1.RequestStatus" json:"decision,omitempty"`
	EncryptedKey  string                 `protobuf:"bytes,4,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToJoinRequestRequest) Reset() {
	*x = RespondToJoinRequestRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToJoinRequestRequest) ProtoMessage() {}

func (x *RespondToJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*RespondToJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{26}
}

func (x *RespondToJoinRequestRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *RespondToJoinRequestRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *RespondToJoinRequestRequest) GetDecision() RequestStatus {
	if x != nil {
		return x.Decision
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *RespondToJoinRequestRequest) GetEncryptedKey() string {
	if x != nil {
		return x.EncryptedKey
	}
	return ""
}

type PendingKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PendingKeys   []*PendingKey          `protobuf:"bytes,1,rep,name=pending_keys,json=pendingKeys,proto3" json:"pending_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingKeysResponse) Reset() {
	*x = PendingKeysResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingKeysResponse) ProtoMessage() {}

func (x *PendingKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingKeysResponse.ProtoReflect.Descriptor instead.
func (*PendingKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{27}
}

func (x *PendingKeysResponse) GetPendingKeys() []*PendingKey {
	if x != nil {
		return x.PendingKeys
	}
	return nil
}

type PendingKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingKey) Reset() {
	*x = PendingKey{}
	mi := &file_proto_room_v1_room_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingKey) ProtoMessage() {}

func (x *PendingKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingKey.ProtoReflect.Descriptor instead.
func (*PendingKey) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{28}
}

func (x *PendingKey) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type AcknowledgeKeyDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeKeyDeliveryRequest) Reset() {
	*x = AcknowledgeKeyDeliveryRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeKeyDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeKeyDeliveryRequest) ProtoMessage() {}

func (x *AcknowledgeKeyDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeKeyDeliveryRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeKeyDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{29}
}

func (x *AcknowledgeKeyDeliveryRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type MarkAsReadRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid          string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	LastReadMessageId string                 `protobuf:"bytes,2,opt,name=last_read_message_id,json=lastReadMessageId,proto3" json:"last_read_message_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{30}
}

func (x *MarkAsReadRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

func (x *MarkAsReadRequest) GetLastReadMessageId() string {
	if x != nil {
		return x.LastReadMessageId
	}
	return ""
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuid      string                 `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{31}
}

func (x *GetUnreadCountRequest) GetRoomUuid() string {
	if x != nil {
		return x.RoomUuid
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{32}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type GetAllowedRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllowedRoomsRequest) Reset() {
	*x = GetAllowedRoomsRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllowedRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllowedRoomsRequest) ProtoMessage() {}

func (x *GetAllowedRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllowedRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetAllowedRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{33}
}

func (x *GetAllowedRoomsRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetAllowedRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomUuids     []string               `protobuf:"bytes,1,rep,name=room_uuids,json=roomUuids,proto3" json:"room_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllowedRoomsResponse) Reset() {
	*x = GetAllowedRoomsResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllowedRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllowedRoomsResponse) ProtoMessage() {}

func (x *GetAllowedRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllowedRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetAllowedRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{34}
}

func (x *GetAllowedRoomsResponse) GetRoomUuids() []string {
	if x != nil {
		return x.RoomUuids
	}
	return nil
}

var File_proto_room_v1_room_proto protoreflect.FileDescriptor

const file_proto_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x18proto/room/v1/room.proto\x12\aroom.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x02\n" +
	"\x04Room\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"b\n" +
	"\n" +
	"RoomMember\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x127\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xd9\x01\n" +
	"\n" +
	"RoomInvite\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\x12\x1b\n" +
	"\troom_uuid\x18\x02 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuses_left\x18\x03 \x01(\x05R\busesLeft\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xed\x01\n" +
	"\vJoinRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.room.v1.RequestStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"a\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_private\x18\x02 \x01(\bR\tisPrivate\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\"l\n" +
	"\x12CreateRoomResponse\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"-\n" +
	"\x0eGetRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"4\n" +
	"\x0fGetRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"H\n" +
	"\x15UpdateRoomNameRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"0\n" +
	"\x11DeleteRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"\x15\n" +
	"\x13GetUserRoomsRequest\"\xf1\x01\n" +
	"\bUserRoom\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_private\x18\x03 \x01(\bR\tisPrivate\x12!\n" +
	"\funread_count\x18\x04 \x01(\x05R\vunreadCount\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x14GetUserRoomsResponse\x12'\n" +
	"\x05rooms\x18\x01 \x03(\v2\x11.room.v1.UserRoomR\x05rooms\"4\n" +
	"\x15GetRoomMembersRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"G\n" +
	"\x16GetRoomMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.room.v1.RoomMemberR\amembers\"/\n" +
	"\x10LeaveRoomRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"O\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"\x8a\x01\n" +
	"\x13CreateInviteRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuses_left\x18\x02 \x01(\x05R\busesLeft\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"3\n" +
	"\x14CreateInviteResponse\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\"/\n" +
	"\x10GetInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\"@\n" +
	"\x11GetInviteResponse\x12+\n" +
	"\x06invite\x18\x01 \x01(\v2\x13.room.v1.RoomInviteR\x06invite\"O\n" +
	"\x13DeleteInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\x12\x1b\n" +
	"\troom_uuid\x18\x02 \x01(\tR\broomUuid\"3\n" +
	"\x14JoinViaInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\"V\n" +
	"\x18CreateJoinRequestRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"5\n" +
	"\x16GetJoinRequestsRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"K\n" +
	"\x17GetJoinRequestsResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.room.v1.JoinRequestR\brequests\"\xb0\x01\n" +
	"\x1bRespondToJoinRequestRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x122\n" +
	"\bdecision\x18\x03 \x01(\x0e2\x16.room.v1.RequestStatusR\bdecision\x12#\n" +
	"\rencrypted_key\x18\x04 \x01(\tR\fencryptedKey\"M\n" +
	"\x13PendingKeysResponse\x126\n" +
	"\fpending_keys\x18\x01 \x03(\v2\x13.room.v1.PendingKeyR\vpendingKeys\")\n" +
	"\n" +
	"PendingKey\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"<\n" +
	"\x1dAcknowledgeKeyDeliveryRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\"a\n" +
	"\x11MarkAsReadRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\x12/\n" +
	"\x14last_read_message_id\x18\x02 \x01(\tR\x11lastReadMessageId\"4\n" +
	"\x15GetUnreadCountRequest\x12\x1b\n" +
	"\troom_uuid\x18\x01 \x01(\tR\broomUuid\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount\"5\n" +
	"\x16GetAllowedRoomsRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"8\n" +
	"\x17GetAllowedRoomsResponse\x12\x1d\n" +
	"\n" +
	"room_uuids\x18\x01 \x03(\tR\troomUuids*\x85\x01\n" +
	"\rRequestStatus\x12\x1e\n" +
	"\x1aREQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REQUEST_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REQUEST_STATUS_ACCEPTED\x10\x02\x12\x1b\n" +
	"\x17REQUEST_STATUS_REJECTED\x10\x032\xec\v\n" +
	"\vRoomService\x12E\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x1b.room.v1.CreateRoomResponse\x12<\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x18.room.v1.GetRoomResponse\x12H\n" +
	"\x0eUpdateRoomName\x12\x1e.room.v1.UpdateRoomNameRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteRoom\x12\x1a.room.v1.DeleteRoomRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\fGetUserRooms\x12\x1c.room.v1.GetUserRoomsRequest\x1a\x1d.room.v1.GetUserRoomsResponse\x12Q\n" +
	"\x0eGetRoomMembers\x12\x1e.room.v1.GetRoomMembersRequest\x1a\x1f.room.v1.GetRoomMembersResponse\x12>\n" +
	"\tLeaveRoom\x12\x19.room.v1.LeaveRoomRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fRemoveMember\x12\x1c.room.v1.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\fCreateInvite\x12\x1c.room.v1.CreateInviteRequest\x1a\x1d.room.v1.CreateInviteResponse\x12B\n" +
	"\tGetInvite\x12\x19.room.v1.GetInviteRequest\x1a\x1a.room.v1.GetInviteResponse\x12D\n" +
	"\fDeleteInvite\x12\x1c.room.v1.DeleteInviteRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rJoinViaInvite\x12\x1d.room.v1.JoinViaInviteRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x11CreateJoinRequest\x12!.room.v1.CreateJoinRequestRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0fGetJoinRequests\x12\x1f.room.v1.GetJoinRequestsRequest\x1a .room.v1.GetJoinRequestsResponse\x12T\n" +
	"\x14RespondToJoinRequest\x12$.room.v1.RespondToJoinRequestRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0eGetPendingKeys\x12\x16.google.protobuf.Empty\x1a\x1c.room.v1.PendingKeysResponse\x12X\n" +
	"\x16AcknowledgeKeyDelivery\x12&.room.v1.AcknowledgeKeyDeliveryRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"MarkAsRead\x12\x1a.room.v1.MarkAsReadRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eGetUnreadCount\x12\x1e.room.v1.GetUnreadCountRequest\x1a\x1f.room.v1.GetUnreadCountResponse\x12T\n" +
	"\x0fGetAllowedRooms\x12\x1f.room.v1.GetAllowedRoomsRequest\x1a .room.v1.GetAllowedRoomsResponseB\x16Z\x14proto/room/v1;roomv1b\x06proto3"

var (
	file_proto_room_v1_room_proto_rawDescOnce sync.Once
	file_proto_room_v1_room_proto_rawDescData []byte
)

func file_proto_room_v1_room_proto_rawDescGZIP() []byte {
	file_proto_room_v1_room_proto_rawDescOnce.Do(func() {
		file_proto_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)))
	})
	return file_proto_room_v1_room_proto_rawDescData
}

var file_proto_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_room_v1_room_proto_goTypes = []any{
	(RequestStatus)(0),                    // 0: room.v1.RequestStatus
	(*Room)(nil),                          // 1: room.v1.Room
	(*RoomMember)(nil),                    // 2: room.v1.RoomMember
	(*RoomInvite)(nil),                    // 3: room.v1.RoomInvite
	(*JoinRequest)(nil),                   // 4: room.v1.JoinRequest
	(*CreateRoomRequest)(nil),             // 5: room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),            // 6: room.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),                // 7: room.v1.GetRoomRequest
	(*GetRoomResponse)(nil),               // 8: room.v1.GetRoomResponse
	(*UpdateRoomNameRequest)(nil),         // 9: room.v1.UpdateRoomNameRequest
	(*DeleteRoomRequest)(nil),             // 10: room.v1.DeleteRoomRequest
	(*GetUserRoomsRequest)(nil),           // 11: room.v1.GetUserRoomsRequest
	(*UserRoom)(nil),                      // 12: room.v1.UserRoom
	(*GetUserRoomsResponse)(nil),          // 13: room.v1.GetUserRoomsResponse
	(*GetRoomMembersRequest)(nil),         // 14: room.v1.GetRoomMembersRequest
	(*GetRoomMembersResponse)(nil),        // 15: room.v1.GetRoomMembersResponse
	(*LeaveRoomRequest)(nil),              // 16: room.v1.LeaveRoomRequest
	(*RemoveMemberRequest)(nil),           // 17: room.v1.RemoveMemberRequest
	(*CreateInviteRequest)(nil),           // 18: room.v1.CreateInviteRequest
	(*CreateInviteResponse)(nil),          // 19: room.v1.CreateInviteResponse
	(*GetInviteRequest)(nil),              // 20: room.v1.GetInviteRequest
	(*GetInviteResponse)(nil),             // 21: room.v1.GetInviteResponse
	(*DeleteInviteRequest)(nil),           // 22: room.v1.DeleteInviteRequest
	(*JoinViaInviteRequest)(nil),          // 23: room.v1.JoinViaInviteRequest
	(*CreateJoinRequestRequest)(nil),      // 24: room.v1.CreateJoinRequestRequest
	(*GetJoinRequestsRequest)(nil),        // 25: room.v1.GetJoinRequestsRequest
	(*GetJoinRequestsResponse)(nil),       // 26: room.v1.GetJoinRequestsResponse
	(*RespondToJoinRequestRequest)(nil),   // 27: room.v1.RespondToJoinRequestRequest
	(*PendingKeysResponse)(nil),           // 28: room.v1.PendingKeysResponse
	(*PendingKey)(nil),                    // 29: room.v1.PendingKey
	(*AcknowledgeKeyDeliveryRequest)(nil), // 30: room.v1.AcknowledgeKeyDeliveryRequest
	(*MarkAsReadRequest)(nil),             // 31: room.v1.MarkAsReadRequest
	(*GetUnreadCountRequest)(nil),         // 32: room.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),        // 33: room.v1.GetUnreadCountResponse
	(*GetAllowedRoomsRequest)(nil),        // 34: room.v1.GetAllowedRoomsRequest
	(*GetAllowedRoomsResponse)(nil),       // 35: room.v1.GetAllowedRoomsResponse
	(*timestamppb.Timestamp)(nil),         // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 37: google.protobuf.Empty
}
var file_proto_room_v1_room_proto_depIdxs = []int32{
	36, // 0: room.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	36, // 1: room.v1.Room.updated_at:type_name -> google.protobuf.Timestamp
	36, // 2: room.v1.RoomMember.joined_at:type_name -> google.protobuf.Timestamp
	36, // 3: room.v1.RoomInvite.expires_at:type_name -> google.protobuf.Timestamp
	36, // 4: room.v1.RoomInvite.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: room.v1.JoinRequest.status:type_name -> room.v1.RequestStatus
	36, // 6: room.v1.JoinRequest.created_at:type_name -> google.protobuf.Timestamp
	36, // 7: room.v1.CreateRoomResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 8: room.v1.GetRoomResponse.room:type_name -> room.v1.Room
	36, // 9: room.v1.UserRoom.joined_at:type_name -> google.protobuf.Timestamp
	36, // 10: room.v1.UserRoom.updated_at:type_name -> google.protobuf.Timestamp
	12, // 11: room.v1.GetUserRoomsResponse.rooms:type_name -> room.v1.UserRoom
	2,  // 12: room.v1.GetRoomMembersResponse.members:type_name -> room.v1.RoomMember
	36, // 13: room.v1.CreateInviteRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 14: room.v1.GetInviteResponse.invite:type_name -> room.v1.RoomInvite
	4,  // 15: room.v1.GetJoinRequestsResponse.requests:type_name -> room.v1.JoinRequest
	0,  // 16: room.v1.RespondToJoinRequestRequest.decision:type_name -> room.v1.RequestStatus
	29, // 17: room.v1.PendingKeysResponse.pending_keys:type_name -> room.v1.PendingKey
	5,  // 18: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	7,  // 19: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	9,  // 20: room.v1.RoomService.UpdateRoomName:input_type -> room.v1.UpdateRoomNameRequest
	10, // 21: room.v1.RoomService.DeleteRoom:input_type -> room.v1.DeleteRoomRequest
	11, // 22: room.v1.RoomService.GetUserRooms:input_type -> room.v1.GetUserRoomsRequest
	14, // 23: room.v1.RoomService.GetRoomMembers:input_type -> room.v1.GetRoomMembersRequest
	16, // 24: room.v1.RoomService.LeaveRoom:input_type -> room.v1.LeaveRoomRequest
	17, // 25: room.v1.RoomService.RemoveMember:input_type -> room.v1.RemoveMemberRequest
	18, // 26: room.v1.RoomService.CreateInvite:input_type -> room.v1.CreateInviteRequest
	20, // 27: room.v1.RoomService.GetInvite:input_type -> room.v1.GetInviteRequest
	22, // 28: room.v1.RoomService.DeleteInvite:input_type -> room.v1.DeleteInviteRequest
	23, // 29: room.v1.RoomService.JoinViaInvite:input_type -> room.v1.JoinViaInviteRequest
	24, // 30: room.v1.RoomService.CreateJoinRequest:input_type -> room.v1.CreateJoinRequestRequest
	25, // 31: room.v1.RoomService.GetJoinRequests:input_type -> room.v1.GetJoinRequestsRequest
	27, // 32: room.v1.RoomService.RespondToJoinRequest:input_type -> room.v1.RespondToJoinRequestRequest
	37, // 33: room.v1.RoomService.GetPendingKeys:input_type -> google.protobuf.Empty
	30, // 34: room.v1.RoomService.AcknowledgeKeyDelivery:input_type -> room.v1.AcknowledgeKeyDeliveryRequest
	31, // 35: room.v1.RoomService.MarkAsRead:input_type -> room.v1.MarkAsReadRequest
	32, // 36: room.v1.RoomService.GetUnreadCount:input_type -> room.v1.GetUnreadCountRequest
	34, // 37: room.v1.RoomService.GetAllowedRooms:input_type -> room.v1.GetAllowedRoomsRequest
	6,  // 38: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomResponse
	8,  // 39: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomResponse
	37, // 40: room.v1.RoomService.UpdateRoomName:output_type -> google.protobuf.Empty
	37, // 41: room.v1.RoomService.DeleteRoom:output_type -> google.protobuf.Empty
	13, // 42: room.v1.RoomService.GetUserRooms:output_type -> room.v1.GetUserRoomsResponse
	15, // 43: room.v1.RoomService.GetRoomMembers:output_type -> room.v1.GetRoomMembersResponse
	37, // 44: room.v1.RoomService.LeaveRoom:output_type -> google.protobuf.Empty
	37, // 45: room.v1.RoomService.RemoveMember:output_type -> google.protobuf.Empty
	19, // 46: room.v1.RoomService.CreateInvite:output_type -> room.v1.CreateInviteResponse
	21, // 47: room.v1.RoomService.GetInvite:output_type -> room.v1.GetInviteResponse
	37, // 48: room.v1.RoomService.DeleteInvite:output_type -> google.protobuf.Empty
	37, // 49: room.v1.RoomService.JoinViaInvite:output_type -> google.protobuf.Empty
	37, // 50: room.v1.RoomService.CreateJoinRequest:output_type -> google.protobuf.Empty
	26, // 51: room.v1.RoomService.GetJoinRequests:output_type -> room.v1.GetJoinRequestsResponse
	37, // 52: room.v1.RoomService.RespondToJoinRequest:output_type -> google.protobuf.Empty
	28, // 53: room.v1.RoomService.GetPendingKeys:output_type -> room.v1.PendingKeysResponse
	37, // 54: room.v1.RoomService.AcknowledgeKeyDelivery:output_type -> google.protobuf.Empty
	37, // 55: room.v1.RoomService.MarkAsRead:output_type -> google.protobuf.Empty
	33, // 56: room.v1.RoomService.GetUnreadCount:output_type -> room.v1.GetUnreadCountResponse
	35, // 57: room.v1.RoomService.GetAllowedRooms:output_type -> room.v1.GetAllowedRoomsResponse
	38, // [38:58] is the sub-list for method output_type
	18, // [18:38] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_room_v1_room_proto_init() }
func file_proto_room_v1_room_proto_init() {
	if File_proto_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_v1_room_proto_goTypes,
		DependencyIndexes: file_proto_room_v1_room_proto_depIdxs,
		EnumInfos:         file_proto_room_v1_room_proto_enumTypes,
		MessageInfos:      file_proto_room_v1_room_proto_msgTypes,
	}.Build()
	File_proto_room_v1_room_proto = out.File
	file_proto_room_v1_room_proto_goTypes = nil
	file_proto_room_v1_room_proto_depIdxs = nil
}
