// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Room Types
type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED RoomType = 0
	RoomType_ROOM_TYPE_DIRECT      RoomType = 1 // 1-on-1 chat
	RoomType_ROOM_TYPE_GROUP       RoomType = 2 // Group chat
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_DIRECT",
		2: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"ROOM_TYPE_DIRECT":      1,
		"ROOM_TYPE_GROUP":       2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_proto_room_v1_room_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{0}
}

// Create Room
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          RoomType               `protobuf:"varint,2,opt,name=type,proto3,enum=room.v1.RoomType" json:"type,omitempty"`
	CreatorUserId string                 `protobuf:"bytes,3,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"` // User creating the room
	MemberUserIds []string               `protobuf:"bytes,4,rep,name=member_user_ids,json=memberUserIds,proto3" json:"member_user_ids,omitempty"` // Initial members (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *CreateRoomRequest) GetMemberUserIds() []string {
	if x != nil {
		return x.MemberUserIds
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Get Room
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=room.v1.RoomType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Room) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Update Room Name
type UpdateRoomNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User performing the update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomNameRequest) Reset() {
	*x = UpdateRoomNameRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomNameRequest) ProtoMessage() {}

func (x *UpdateRoomNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoomNameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoomNameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Delete Room
type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User performing the delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeleteRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Join Room
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Leave Room
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Get Room Members
type GetRoomMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersRequest) Reset() {
	*x = GetRoomMembersRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersRequest) ProtoMessage() {}

func (x *GetRoomMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersRequest.ProtoReflect.Descriptor instead.
func (*GetRoomMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoomMembersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	mi := &file_proto_room_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *RoomMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type GetRoomMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*RoomMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersResponse) Reset() {
	*x = GetRoomMembersResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersResponse) ProtoMessage() {}

func (x *GetRoomMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersResponse.ProtoReflect.Descriptor instead.
func (*GetRoomMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomMembersResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// Get User Rooms
type GetUserRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoomsRequest) Reset() {
	*x = GetUserRoomsRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomsRequest) ProtoMessage() {}

func (x *GetUserRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRoomsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=room.v1.RoomType" json:"type,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoom) Reset() {
	*x = UserRoom{}
	mi := &file_proto_room_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoom) ProtoMessage() {}

func (x *UserRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoom.ProtoReflect.Descriptor instead.
func (*UserRoom) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *UserRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRoom) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *UserRoom) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *UserRoom) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *UserRoom) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetUserRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*UserRoom            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoomsResponse) Reset() {
	*x = GetUserRoomsResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomsResponse) ProtoMessage() {}

func (x *GetUserRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRoomsResponse) GetRooms() []*UserRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// Mark As Read
type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsReadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Get Unread Count
type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_proto_room_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{16}
}

func (x *GetUnreadCountRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetUnreadCountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_proto_room_v1_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_v1_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_v1_room_proto_rawDescGZIP(), []int{17}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_proto_room_v1_room_proto protoreflect.FileDescriptor

const file_proto_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x18proto/room/v1/room.proto\x12\aroom.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.room.v1.RoomTypeR\x04type\x12&\n" +
	"\x0fcreator_user_id\x18\x03 \x01(\tR\rcreatorUserId\x12&\n" +
	"\x0fmember_user_ids\x18\x04 \x03(\tR\rmemberUserIds\"h\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xf3\x01\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.room.v1.RoomTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\"4\n" +
	"\x0fGetRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"]\n" +
	"\x15UpdateRoomNameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"E\n" +
	"\x11DeleteRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"C\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x15GetRoomMembersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"^\n" +
	"\n" +
	"RoomMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"G\n" +
	"\x16GetRoomMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.room.v1.RoomMemberR\amembers\".\n" +
	"\x13GetUserRoomsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf5\x01\n" +
	"\bUserRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.room.v1.RoomTypeR\x04type\x12!\n" +
	"\funread_count\x18\x04 \x01(\x05R\vunreadCount\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x14GetUserRoomsResponse\x12'\n" +
	"\x05rooms\x18\x01 \x03(\v2\x11.room.v1.UserRoomR\x05rooms\"E\n" +
	"\x11MarkAsReadRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount*P\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROOM_TYPE_DIRECT\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x022\xd1\x05\n" +
	"\vRoomService\x12E\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x1b.room.v1.CreateRoomResponse\x12<\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x18.room.v1.GetRoomResponse\x12H\n" +
	"\x0eUpdateRoomName\x12\x1e.room.v1.UpdateRoomNameRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteRoom\x12\x1a.room.v1.DeleteRoomRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bJoinRoom\x12\x18.room.v1.JoinRoomRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\tLeaveRoom\x12\x19.room.v1.LeaveRoomRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eGetRoomMembers\x12\x1e.room.v1.GetRoomMembersRequest\x1a\x1f.room.v1.GetRoomMembersResponse\x12K\n" +
	"\fGetUserRooms\x12\x1c.room.v1.GetUserRoomsRequest\x1a\x1d.room.v1.GetUserRoomsResponse\x12@\n" +
	"\n" +
	"MarkAsRead\x12\x1a.room.v1.MarkAsReadRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eGetUnreadCount\x12\x1e.room.v1.GetUnreadCountRequest\x1a\x1f.room.v1.GetUnreadCountResponseB\x16Z\x14proto/room/v1;roomv1b\x06proto3"

var (
	file_proto_room_v1_room_proto_rawDescOnce sync.Once
	file_proto_room_v1_room_proto_rawDescData []byte
)

func file_proto_room_v1_room_proto_rawDescGZIP() []byte {
	file_proto_room_v1_room_proto_rawDescOnce.Do(func() {
		file_proto_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)))
	})
	return file_proto_room_v1_room_proto_rawDescData
}

var file_proto_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_room_v1_room_proto_goTypes = []any{
	(RoomType)(0),                  // 0: room.v1.RoomType
	(*CreateRoomRequest)(nil),      // 1: room.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),     // 2: room.v1.CreateRoomResponse
	(*GetRoomRequest)(nil),         // 3: room.v1.GetRoomRequest
	(*Room)(nil),                   // 4: room.v1.Room
	(*GetRoomResponse)(nil),        // 5: room.v1.GetRoomResponse
	(*UpdateRoomNameRequest)(nil),  // 6: room.v1.UpdateRoomNameRequest
	(*DeleteRoomRequest)(nil),      // 7: room.v1.DeleteRoomRequest
	(*JoinRoomRequest)(nil),        // 8: room.v1.JoinRoomRequest
	(*LeaveRoomRequest)(nil),       // 9: room.v1.LeaveRoomRequest
	(*GetRoomMembersRequest)(nil),  // 10: room.v1.GetRoomMembersRequest
	(*RoomMember)(nil),             // 11: room.v1.RoomMember
	(*GetRoomMembersResponse)(nil), // 12: room.v1.GetRoomMembersResponse
	(*GetUserRoomsRequest)(nil),    // 13: room.v1.GetUserRoomsRequest
	(*UserRoom)(nil),               // 14: room.v1.UserRoom
	(*GetUserRoomsResponse)(nil),   // 15: room.v1.GetUserRoomsResponse
	(*MarkAsReadRequest)(nil),      // 16: room.v1.MarkAsReadRequest
	(*GetUnreadCountRequest)(nil),  // 17: room.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil), // 18: room.v1.GetUnreadCountResponse
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 20: google.protobuf.Empty
}
var file_proto_room_v1_room_proto_depIdxs = []int32{
	0,  // 0: room.v1.CreateRoomRequest.type:type_name -> room.v1.RoomType
	19, // 1: room.v1.CreateRoomResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: room.v1.Room.type:type_name -> room.v1.RoomType
	19, // 3: room.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: room.v1.Room.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: room.v1.GetRoomResponse.room:type_name -> room.v1.Room
	19, // 6: room.v1.RoomMember.joined_at:type_name -> google.protobuf.Timestamp
	11, // 7: room.v1.GetRoomMembersResponse.members:type_name -> room.v1.RoomMember
	0,  // 8: room.v1.UserRoom.type:type_name -> room.v1.RoomType
	19, // 9: room.v1.UserRoom.joined_at:type_name -> google.protobuf.Timestamp
	19, // 10: room.v1.UserRoom.updated_at:type_name -> google.protobuf.Timestamp
	14, // 11: room.v1.GetUserRoomsResponse.rooms:type_name -> room.v1.UserRoom
	1,  // 12: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	3,  // 13: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	6,  // 14: room.v1.RoomService.UpdateRoomName:input_type -> room.v1.UpdateRoomNameRequest
	7,  // 15: room.v1.RoomService.DeleteRoom:input_type -> room.v1.DeleteRoomRequest
	8,  // 16: room.v1.RoomService.JoinRoom:input_type -> room.v1.JoinRoomRequest
	9,  // 17: room.v1.RoomService.LeaveRoom:input_type -> room.v1.LeaveRoomRequest
	10, // 18: room.v1.RoomService.GetRoomMembers:input_type -> room.v1.GetRoomMembersRequest
	13, // 19: room.v1.RoomService.GetUserRooms:input_type -> room.v1.GetUserRoomsRequest
	16, // 20: room.v1.RoomService.MarkAsRead:input_type -> room.v1.MarkAsReadRequest
	17, // 21: room.v1.RoomService.GetUnreadCount:input_type -> room.v1.GetUnreadCountRequest
	2,  // 22: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomResponse
	5,  // 23: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomResponse
	20, // 24: room.v1.RoomService.UpdateRoomName:output_type -> google.protobuf.Empty
	20, // 25: room.v1.RoomService.DeleteRoom:output_type -> google.protobuf.Empty
	20, // 26: room.v1.RoomService.JoinRoom:output_type -> google.protobuf.Empty
	20, // 27: room.v1.RoomService.LeaveRoom:output_type -> google.protobuf.Empty
	12, // 28: room.v1.RoomService.GetRoomMembers:output_type -> room.v1.GetRoomMembersResponse
	15, // 29: room.v1.RoomService.GetUserRooms:output_type -> room.v1.GetUserRoomsResponse
	20, // 30: room.v1.RoomService.MarkAsRead:output_type -> google.protobuf.Empty
	18, // 31: room.v1.RoomService.GetUnreadCount:output_type -> room.v1.GetUnreadCountResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_room_v1_room_proto_init() }
func file_proto_room_v1_room_proto_init() {
	if File_proto_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_v1_room_proto_rawDesc), len(file_proto_room_v1_room_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_v1_room_proto_goTypes,
		DependencyIndexes: file_proto_room_v1_room_proto_depIdxs,
		EnumInfos:         file_proto_room_v1_room_proto_enumTypes,
		MessageInfos:      file_proto_room_v1_room_proto_msgTypes,
	}.Build()
	File_proto_room_v1_room_proto = out.File
	file_proto_room_v1_room_proto_goTypes = nil
	file_proto_room_v1_room_proto_depIdxs = nil
}
